name: assets_audio_player_web
description: Web plugin for assets_audio_player, play music/audio stored in assets files directly from Flutter.
version: 3.1.1
#author: Florent Champigny <champigny.florent@gmail.com>
homepage: https://github.com/florent37/Flutter-AssetsAudioPlayer

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      web:
        pluginClass: AssetsAudioPlayerWebPlugin
        fileName: web/assets_audio_player_web.dart
