name: assets_audio_player_example
description: Demonstrates how to use the assets_audio_player plugin.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic: ^1.0.5+1

  # for local file test
  dio: 3.0.9
  path_provider: ^1.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_web_compilers: '>=1.0.0 <2.0.0'

  # uncomment to use remote repos
  # assets_audio_player: 1.3.5+2
  # assets_audio_player_web: 1.3.5+3

  # uncomment to match local repos
  assets_audio_player:
   path: ../
  assets_audio_player_web:
    path: ../assets_audio_player_web

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/
  fonts:
    - family:  AssetAudioPlayer
      fonts:
        - asset: fonts/AssetAudioPlayer.ttf
